name: Run Tests
on:

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: npm run tests
        run: |
          npm run test
      - name: Comment Test Coverage
      uses: codecov/codecov-action@v1
        with:
          file: coverage/every-bus/lcov.info
          name: codecov-umbrella 
          fail_ci_if_error: true 
          verbose: true 
      